### ISSUE TITLE
최근 인스타그램 크롤링이 되지 않아 문의드립니다!

### ISSUE THREAD

**Issue by silber60** [needleworm/bhban_RPA#2]
폴더 5_10_7과 5_10_8이 되지 않고
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
라는 에러와 함께
뷰파인더를 누르지 못하고 계속 종료 됩니다.
도와주시면 감사드리겠습니다.

**Comment by needleworm** [comment]
안녕하십니까. 소중한 문의 감사드립니다.
제 쪽에서 에러 재현이 잘 안 되는데, 혹시 해당 프로젝트들 실행시 어디까지 실행이 되고 어디서 중단되는지 알려주실 수 있으신가요?

**Comment by silber60** [comment]
네! 로그인하고 게시글을 갖고 오는 것까진 문제가 없으나
좋아요부터 눌리지 않더라구요.
 
파이썬에서 긁어오느라 글자가 좀 깨지는데 오류내역도 함께 전달드립니다!
Process Start.
Traceback (most recent call last):
  File "D:\▒▒\bhban_RPA\[Part 5] ▒▒ũ▒δ▒ ▒ؾ▒▒! ▒▒帮▒▒ ▒ڵ▒ȭ▒▒ ▒▒▒Ͽ▒\[Chapter 10] ▒▒▒ͳ▒ ▒ڵ▒ȭ ▒߱▒ - HTML▒▒ ▒▒▒▒ ▒▒ ▒▒ ▒ִ▒ HTML ũ▒Ѹ▒\5_10_7_▒▒ũ▒▒ ▒▒▒▒ ▒ν▒Ÿ▒׷▒▒▒▒▒ Ư▒▒ ▒±װ▒ ▒޸▒ ▒Խù▒ ▒▒▒▒▒▒ ▒▒▒ƿ▒ ▒▒▒▒▒▒\main.py", line 39, in <module>
    BOT.insta_jungdok(tag, NUMBER)
  File "D:\▒▒\bhban_RPA\[Part 5] ▒▒ũ▒δ▒ ▒ؾ▒▒! ▒▒帮▒▒ ▒ڵ▒ȭ▒▒ ▒▒▒Ͽ▒\[Chapter 10] ▒▒▒ͳ▒ ▒ڵ▒ȭ ▒߱▒ - HTML▒▒ ▒▒▒▒ ▒▒ ▒▒ ▒ִ▒ HTML ũ▒Ѹ▒\5_10_7_▒▒ũ▒▒ ▒▒▒▒ ▒ν▒Ÿ▒׷▒▒▒▒▒ Ư▒▒ ▒±װ▒ ▒޸▒ ▒Խù▒ ▒▒▒▒▒▒ ▒▒▒ƿ▒ ▒▒▒▒▒▒\insta_bot_like.py", line 113, in insta_jungdok
    self.press_like(num)
  File "D:\▒▒\bhban_RPA\[Part 5] ▒▒ũ▒δ▒ ▒ؾ▒▒! ▒▒帮▒▒ ▒ڵ▒ȭ▒▒ ▒▒▒Ͽ▒\[Chapter 10] ▒▒▒ͳ▒ ▒ڵ▒ȭ ▒߱▒ - HTML▒▒ ▒▒▒▒ ▒▒ ▒▒ ▒ִ▒ HTML ũ▒Ѹ▒\5_10_7_▒▒ũ▒▒ ▒▒▒▒ ▒ν▒Ÿ▒׷▒▒▒▒▒ Ư▒▒ ▒±װ▒ ▒޸▒ ▒Խù▒ ▒▒▒▒▒▒ ▒▒▒ƿ▒ ▒▒▒▒▒▒\insta_bot_like.py", line 92, in press_like
    el.click()
  File "C:\Users\ȸ▒▒-02\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\ȸ▒▒-02\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\ȸ▒▒-02\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ȸ▒▒-02\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=94.0.4606.81)
 
친절하게 대답들어주시는 점, 감사드립니다!
 
제가 좀 손대다가 문제가 더 많아져서
-----Original Message-----

**Comment by silber60** [comment]
다 지우고 시행해보아도

$ python main.py soojeong1201 aiaidambi0708 혼술 100
Process Start.
Traceback (most recent call last):
  File "C:\Users\▒▒▒▒▒ PM\Desktop\bhban_RPA\[Part 5] ▒▒ũ▒δ▒ ▒ؾ▒▒! ▒▒帮▒▒ ▒ڵ▒ȭ▒▒ ▒▒▒Ͽ▒\[Chapter 10] ▒▒▒ͳ▒ ▒ڵ▒ȭ ▒߱▒ - HTML▒▒ ▒▒▒▒ ▒▒ ▒▒ ▒ִ▒ HTML ũ▒Ѹ▒\5_10_7_▒▒ũ▒▒ ▒▒▒▒ ▒ν▒Ÿ▒׷▒▒▒▒▒ Ư▒▒ ▒±װ▒ ▒޸▒ ▒Խù▒ ▒▒▒▒▒▒ ▒▒▒ƿ▒ ▒▒▒▒▒▒\main.py", line 39, in <module>
    BOT.insta_jungdok(tag, NUMBER)
  File "C:\Users\▒▒▒▒▒ PM\Desktop\bhban_RPA\[Part 5] ▒▒ũ▒δ▒ ▒ؾ▒▒! ▒▒帮▒▒ ▒ڵ▒ȭ▒▒ ▒▒▒Ͽ▒\[Chapter 10] ▒▒▒ͳ▒ ▒ڵ▒ȭ ▒߱▒ - HTML▒▒ ▒▒▒▒ ▒▒ ▒▒ ▒ִ▒ HTML ũ▒Ѹ▒\5_10_7_▒▒ũ▒▒ ▒▒▒▒ ▒ν▒Ÿ▒׷▒▒▒▒▒ Ư▒▒ ▒±װ▒ ▒޸▒ ▒Խù▒ ▒▒▒▒▒▒ ▒▒▒ƿ▒ ▒▒▒▒▒▒\insta_bot_like.py", line 114, in insta_jungdok
    self.press_like(num)
  File "C:\Users\▒▒▒▒▒ PM\Desktop\bhban_RPA\[Part 5] ▒▒ũ▒δ▒ ▒ؾ▒▒! ▒▒帮▒▒ ▒ڵ▒ȭ▒▒ ▒▒▒Ͽ▒\[Chapter 10] ▒▒▒ͳ▒ ▒ڵ▒ȭ ▒߱▒ - HTML▒▒ ▒▒▒▒ ▒▒ ▒▒ ▒ִ▒ HTML ũ▒Ѹ▒\5_10_7_▒▒ũ▒▒ ▒▒▒▒ ▒ν▒Ÿ▒׷▒▒▒▒▒ Ư▒▒ ▒±װ▒ ▒޸▒ ▒Խù▒ ▒▒▒▒▒▒ ▒▒▒ƿ▒ ▒▒▒▒▒▒\insta_bot_like.py", line 93, in press_like
    el.click()
  File "C:\Users\▒▒▒▒▒ PM\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\▒▒▒▒▒ PM\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 693, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\▒▒▒▒▒ PM\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\▒▒▒▒▒ PM\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=95.0.4638.69)
Stacktrace:
Backtrace:
        Ordinal0 [0x01090C43+2493507]
        Ordinal0 [0x0102A4B1+2073777]
        Ordinal0 [0x00F324D0+1058000]
        Ordinal0 [0x00F5D914+1235220]
        Ordinal0 [0x00F53787+1193863]
        Ordinal0 [0x00F75943+1333571]
        Ordinal0 [0x00F535A6+1193382]
        Ordinal0 [0x00F75A2A+1333802]
        Ordinal0 [0x00F85038+1396792]
        Ordinal0 [0x00F7580B+1333259]
        Ordinal0 [0x00F52314+1188628]
        Ordinal0 [0x00F5316F+1192303]
        GetHandleVerifier [0x01217BF6+1548950]
        GetHandleVerifier [0x012C461C+2256060]
        GetHandleVerifier [0x0111C13B+518107]
        GetHandleVerifier [0x0111B1E0+514176]
        Ordinal0 [0x0102F53D+2094397]
        Ordinal0 [0x01033418+2110488]
        Ordinal0 [0x01033552+2110802]
        Ordinal0 [0x0103CE81+2150017]
        BaseThreadInitThunk [0x765BFA29+25]
        RtlGetAppContainerNamedObjectPath [0x772B7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x772B7A6E+238]


라고 뜹니다. 혹여 아시는 바 있으시면 도움 요청드립니다
